### ISSUE TITLE
visionOS support: compilation warnings in xcode 14.3.1

### ISSUE THREAD

**Issue by codeactual** [TelemetryDeck/SwiftSDK#111]
`Sources/TelemetryClient/Signal.swift` emits two `Unknown operating system for build configuration 'os'` warnings in xcode 14.3.1 because `os(xrOS)` isn't recognized.

**Comment by winsmith** [comment]
Thanks! How annoying are the warnings? I feel like it's better to be prepared for xrOS at the cost of a bit of discomfort, but if it's driving you up the walls I can change my mind :D~
