### ISSUE TITLE
[iOS] "newSessionBegan" is not tracked on app launch for older apps without `SceneDelegate`

### ISSUE THREAD

**Issue by dreymonde** [TelemetryDeck/SwiftSDK#113]
Quoting the code:

```swift
    /// If `true`, sends a "newSessionBegan" Signal on each app foreground or cold launch
    ///
    /// Defaults to true. Set to false to prevent automatically sending this signal.
    public var sendNewSessionBeganSignal: Bool = true
```

It relies on `UIApplication.willEnterForegroundNotification`, and, for some reason, allegedly since iOS 14 for apps that do not support `SceneDelegate`, this notification is _not_ fired on launch, puzzlingly. And considering that there are still many such apps like it out there, I think this should be addressed.

I've made a simple minimal example project that reproduces this issue. Setting a breakpoint at `func processSignal(_ signalType: TelemetrySignalType, for clientUser: String? = nil, floatValue: Double? = nil, with additionalPayload: [String: String] = [:], configuration: TelemetryManagerConfiguration)` will quickly show that the event is not being fired

[TelemetryDeckNewSessionReproduce.zip](https://github.com/TelemetryDeck/SwiftClient/files/12346325/TelemetryDeckNewSessionReproduce.zip)

Let me know if you have any questions

**Comment by dreymonde** [comment]
For additional context: https://stackoverflow.com/questions/65618945/uiapplication-didbecomeactivenotification-not-called-ios-14

**Comment by winsmith** [comment]
Thanks for this report! I'll look into it!
