### ISSUE TITLE
LogHandler Initialiser Not Public

### ISSUE THREAD

**Issue by Sherlouk** [TelemetryDeck/SwiftSDK#123]
It's not actually possible (from what I can tell) to override the `LogHandler` implementation as there's no public initialiser.

I want to replace it with an OS Logger implementation to get the benefit of Xcode 15's colour output.

> Logger(subsystem: Bundle.main.bundleIdentifier!, category: "TelemetryDeck")

**Comment by winsmith** [comment]
Ooh smart, I love it! Wanna make a PR?

**Comment by Sherlouk** [comment]
Sorry for delay, opened PR.

**Comment by jordibruin** [comment]
Can this be merged @winsmith ? Right now it's not possible to change the loglevel
