### ISSUE TITLE
Add support for CocoaPods

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftSDK#125]
Required for https://github.com/TelemetryDeck/Issues/issues/190#top

**Comment by 0xWDG** [comment]
Hi,

Just a head up that cocoapods is in "Maintance mode"

https://blog.cocoapods.org/CocoaPods-Support-Plans/

> E.g. I maintain Unity, React Native, Flutter etc. A lot of these projects will (and should) be migrating to Swift Package Manager with time. As specified above, we are not breaking anything but bugs you may raise are unlikely to get fixed.

**Comment by philliptharris** [comment]
Yes, drop support for CocoaPods.

**Comment by Jeehut** [comment]
@philliptharris It seems that we can't remove the CocoaPods deployment just yet due to our Flutter SDK depending on it, see https://github.com/TelemetryDeck/FlutterSDK/issues/21.

But having that said, since we already have CocoaPods support, I'm going to close this issue.
