### ISSUE TITLE
HSTS for main (null) in visionOS

### ISSUE THREAD

**Issue by mikaelacaron** [TelemetryDeck/SwiftSDK#138]
When I added Telemetry Deck via SPM to my visionOS project this was printing in the console

It appears as if the signals are sending properly, so I'm not sure what this relates to.

```
https://nom.telemetrydeck.com/api/v1/apps/{uuid}/signals/multiple/ is NOT allowed to set HSTS for main doc (null)
```

(not sure if the uuid is secret)

I was running visionOS v1.0 in the simulator on Xcode 15.2

**Comment by winsmith** [comment]
I've had this too in the betas but couldn't reproduce it with visionOS > 1.0. Is this still happening to your project?

**Comment by mikaelacaron** [comment]
I just put my Vision Pro on 2.0, I could check in the simulator though?

**Comment by mikaelacaron** [comment]
Gonna close this, cause I haven't seen it in a while / haven't been looking. I'll open a new issue if I see it again
