### ISSUE TITLE
I/O on the main thread

### ISSUE THREAD

**Issue by magnusburton** [TelemetryDeck/SwiftSDK#148]
I'm getting the following runtime warning in Xcode at the referenced line.

> This code path does I/O on the main thread underneath that can lead to UI responsiveness issues. Consider ways to optimize this code path

https://github.com/TelemetryDeck/SwiftClient/blob/ab7455cc763da7f0b9d8803682a362ac78aafdec/Sources/TelemetryClient/SignalCache.swift#L73

**Comment by dpelletier2017** [comment]
Same error here.
Xcode 15.3, iOS 17.2 target.

**Comment by borisyurkevich** [comment]
@winsmith what is the reason it's closed? I am also getting this `fault` in my app.
