### ISSUE TITLE
Custom logging strategy not working

### ISSUE THREAD

**Issue by davidrothera** [TelemetryDeck/SwiftSDK#151]
In the documentation (https://github.com/TelemetryDeck/SwiftClient#custom-logging-strategy) it states that users can customise the logging handler for working with things like `swift-log` however this is not possible due to an internal protection level on the `LogHandler` initialiser.

```
'LogHandler' initializer is inaccessible due to 'internal' protection level
```

**Comment by Jeehut** [comment]
This was fixed in https://github.com/TelemetryDeck/SwiftSDK/pull/128. Closing! 🙌
