### ISSUE TITLE
EXC_BAD_ACCESS crash in iOS 16.4 simulator on call to TelemetryDeck.purchaseCompleted 

### ISSUE THREAD

**Issue by measuredweighed** [TelemetryDeck/SwiftSDK#158]
I'm seeing a reproducible crash when calling `TelemetryDeck.purchaseCompleted` in the iOS 16.4 simulator using version `2.1.1` of the TelemetryClient from SPM. Purchases appear to be logged correctly in iOS 17+. The crash seems to happen when calling `StoreKit.Transaction`'s `currencyCode` getter. It appears there's been some [recent work](https://github.com/TelemetryDeck/SwiftSDK/commit/1db5ef4f22ba08a8eccd121094808e9eab0c44fc) in this area that may be related.

<img width="1285" alt="EXC_BAD_ACCESS" src="https://github.com/TelemetryDeck/SwiftSDK/assets/1234600/c3887fb0-af8c-413b-ae5d-51a10f22b1f9">

**Comment by Jeehut** [comment]
@measuredweighed Do you know if this also happens on a real device?

**Comment by measuredweighed** [comment]
No, sorry, I didn't have a chance to run this on an actual iOS 16 device. I was evaluating TelemetryDeck and testing solely via the simulator/Xcode environment, which is how we tend to do the bulk of our In App Purchase testing before final device checks.

**Comment by Jeehut** [comment]
@measuredweighed Thank you for the extra info and sorry for the delay. I just returned from a trip to Cupertino for WWDC and this was the first task I picked up. Thanks to your aded information, I was able to reproduce the bug and fix it.

It seems that Apple forgot to keep the deprecated (but not removed!) APIs within the simulator, so I made sure to use the new APIs on devices where with newer OS (16.0 and newer). In my demo project this fixed the issue as it's no longer calling `currencyCode`. I'll be releasing version `2.2.1` of the SDK shortly with the fix. Please let me know if the issue still occurs.
