### ISSUE TITLE
Add MainActor Annotation an Shared Navigation Path Singleton

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftSDK#172]
We added a new singleton that stores the shared navigation path. A customer commented that we should probable mark that as `@MainActor` to eliminate any chance for race conditions. 

Is this a good idea? cc @Jeehut

**Comment by Jeehut** [comment]
@winsmith I am not very experienced with Swift 6 actors behavior myself, but it does sound like a good idea since navigation path is related to UI and UI is handled in the main thread.

**Comment by winsmith** [comment]
Awesome, could you add that next time you're in the vicinity of that code please?

**Comment by Jeehut** [comment]
Done: https://github.com/TelemetryDeck/SwiftSDK/pull/173

**Comment by Jeehut** [comment]
This is now implemented and merged as part of #174.
