### ISSUE TITLE
Get rid of all the deprecation warnings within the SDK

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/SwiftSDK#176]
To keep things simple and the reduce changes for review, I had decided to keep all the existing implementations unchanged in the grand rename PR #149. But as consequence of this decision, we now have lots of deprecation warnings within the SDK itself, because old API implementations still call into old APIs. While this is not a blocker in any way, these warnings distract from other potentially more important warnings which can then be overlooked easily, so we should actually update all calls to the new API naming and get rid of all these warnings:

<img width="1050" alt="Bildschirmfoto 2024-07-31 um 17 15 25" src="https://github.com/user-attachments/assets/ccdb519e-b202-40a5-b6cb-f5f475a84b65">

**Comment by ddaddy** [comment]
I just came here to request the same.
I have a peculiar situation, in that my macOS app supports all the way back to `10.11` and thus I cannot use `SPM`.
I manually add all the files to my project which has worked great for a while, but after updating everything to the latest version I get all the deprecation warnings from within the `TelemetryDeck` files.

I have managed to fix a few of them, like the ones in the `@objc(TelemetryManager)` section. But the calls in the `enum TelemetryDeck` section require more work as the `fix it` just causes an infinite recursion.

**Comment by Jeehut** [comment]
@ddaddy I have this task on my roadmap already and just moved it higher up based on your feedback. I thought it's a pure "internal" issue, but if real customers are affected, I will fix them faster.

As far as implementation goes, basically my way to address these warnings will be to move all the logic inside the deprecated methods into the new variants and instead of calling the deprecated ones from the new ones, to call the new ones from the deprecated ones. That should fix all warnings. But it's also a bigger task, which is why I didn't do it during the Swift 6 migration task right away.

**Comment by ddaddy** [comment]
That’s exactly what I was thinking when I had a look at it, but there were a couple that stumped me and I didn’t know much about what had changed between old and new, so thought it best to leave for you.
