### ISSUE TITLE
What’s the purpose of trackNavigation(_)

### ISSUE THREAD

**Issue by ddaddy** [TelemetryDeck/SwiftSDK#205]
I’ve implemented the new `. trackNavigation(_)` modifier in some of my SiftUI views, but I don’t see these anywhere on the TelemetryDeck web dashboard. Where do we view these?

Also, is there similar for UIKit, or do we just send a standard signal?

**Comment by Jeehut** [comment]
@ddaddy I believe all your questions are answered in the following documentation page, including what it's for. Please check it out: https://telemetrydeck.com/docs/articles/navigation-signals/

Closing for now, let me know if you have any further questions!
