### ISSUE TITLE
Feature request: add display scale factor to default parameters

### ISSUE THREAD

**Issue by daprice** [TelemetryDeck/SwiftSDK#210]
Since `TelemetryDeck.Device.screenResolutionWidth` and `screenResolutionHeight` are in points, not pixels, it always reports 1080p on tvOS no matter what, even if the TV is 4k. Adding the display scale (e.g. `UIScreen.main.scale`) would allow differentiating between the two resolutions without having to change how the existing width and height parameters are measured.

Also for macOS, it might be helpful to be able to tell what percentage of users are on retina displays.

**Comment by Jeehut** [comment]
@daprice Thank you for the great suggestion. This has been implemented as of #213 and should be merged & releases soon!

**Comment by Jeehut** [comment]
@daprice I'm happy to inform you that the feature is now part of the [new SDK release 2.6.0](https://github.com/TelemetryDeck/SwiftSDK/releases/tag/2.6.0).

Please give it a try and let me know if this works for you! The field is called `TelemetryDeck.Device.screenScaleFactor`. Thank you again for requesting this. 🙏
