### ISSUE TITLE
Rename SDK to TelemetryDeck SDK

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftSDK#45]

**Comment by Sherlouk** [comment]
Is this still needed Daniel? I assume this means renaming away from "TelemetryClient"?

**Comment by winsmith** [comment]
I keep waffling on this. All the other SDKs are called "TelemetryDeckSDK" but the Swift one isn't. But I'm afraid it's gonna break a bunch of apps if they update, and it's also kinda not worth it.

**Comment by Sherlouk** [comment]
Would certainly be a breaking change, and so would be best to wait until there are other technical reasons for wanting to release a v2.0.0. 

Perhaps worth setting up a milestone to keep track of that release? (though given the current issues and feature requests, this could be a while off and if you're not frantic on getting it sorted could be something to put on the backburner!)

**Comment by winsmith** [comment]
I've put it on the internal roadmap (which, come to think of it, I wanted to make public at some point – I'll see to that)

**Comment by Jeehut** [comment]
What you could is rename this to `TelemetryDeckSDK` and create a new target `TelemetryDeck` with the old name which only contains an `Exports.swift` file doing a `@_exported import TelemetryDeckSDK`. Then, people using the old name should be able to continue doing `import TelemetryDeck`, but new users would import the renamed `TelemetryDeckSDK` module directly. While `@_exported` is not officially a Swift feature yet, it's used in such core places within the Swift ecosystem that one can assume it will become an official feature at some point. Just an idea, in case you still care.

**Comment by winsmith** [comment]
Can this be closed @Jeehut ?

**Comment by Jeehut** [comment]
I believe so, yeah. 🎉 As per #189.
